---
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run package tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5

      - name: run tests
        run: ./bin/package_tests.sh
